//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCuentas.WSGetEstadoCuenta {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:soap-fault:details")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:solpdf", ConfigurationName="WSGetEstadoCuenta.solpdfObj")]
    public interface solpdfObj {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BBCuentas.WSGetEstadoCuenta.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BBCuentas.WSGetEstadoCuenta.wsSolpdfResponse wsSolpdf(BBCuentas.WSGetEstadoCuenta.wsSolpdfRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BBCuentas.WSGetEstadoCuenta.wsSolpdfResponse> wsSolpdfAsync(BBCuentas.WSGetEstadoCuenta.wsSolpdfRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsSolpdf", WrapperNamespace="urn:solpdf:solpdf", IsWrapped=true)]
    public partial class wsSolpdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:solpdf:solpdf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipiEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:solpdf:solpdf", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipiGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:solpdf:solpdf", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipiCliente;
        
        public wsSolpdfRequest() {
        }
        
        public wsSolpdfRequest(System.Nullable<int> ipiEmpresa, System.Nullable<int> ipiGrupo, System.Nullable<int> ipiCliente) {
            this.ipiEmpresa = ipiEmpresa;
            this.ipiGrupo = ipiGrupo;
            this.ipiCliente = ipiCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsSolpdfResponse", WrapperNamespace="urn:solpdf:solpdf", IsWrapped=true)]
    public partial class wsSolpdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:solpdf:solpdf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:solpdf:solpdf", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> opiCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:solpdf:solpdf", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string opcMensaje;
        
        public wsSolpdfResponse() {
        }
        
        public wsSolpdfResponse(string result, System.Nullable<int> opiCodigo, string opcMensaje) {
            this.result = result;
            this.opiCodigo = opiCodigo;
            this.opcMensaje = opcMensaje;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface solpdfObjChannel : BBCuentas.WSGetEstadoCuenta.solpdfObj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class solpdfObjClient : System.ServiceModel.ClientBase<BBCuentas.WSGetEstadoCuenta.solpdfObj>, BBCuentas.WSGetEstadoCuenta.solpdfObj {
        
        public solpdfObjClient() {
        }
        
        public solpdfObjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public solpdfObjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public solpdfObjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public solpdfObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BBCuentas.WSGetEstadoCuenta.wsSolpdfResponse BBCuentas.WSGetEstadoCuenta.solpdfObj.wsSolpdf(BBCuentas.WSGetEstadoCuenta.wsSolpdfRequest request) {
            return base.Channel.wsSolpdf(request);
        }
        
        public string wsSolpdf(System.Nullable<int> ipiEmpresa, System.Nullable<int> ipiGrupo, System.Nullable<int> ipiCliente, out System.Nullable<int> opiCodigo, out string opcMensaje) {
            BBCuentas.WSGetEstadoCuenta.wsSolpdfRequest inValue = new BBCuentas.WSGetEstadoCuenta.wsSolpdfRequest();
            inValue.ipiEmpresa = ipiEmpresa;
            inValue.ipiGrupo = ipiGrupo;
            inValue.ipiCliente = ipiCliente;
            BBCuentas.WSGetEstadoCuenta.wsSolpdfResponse retVal = ((BBCuentas.WSGetEstadoCuenta.solpdfObj)(this)).wsSolpdf(inValue);
            opiCodigo = retVal.opiCodigo;
            opcMensaje = retVal.opcMensaje;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<BBCuentas.WSGetEstadoCuenta.wsSolpdfResponse> wsSolpdfAsync(BBCuentas.WSGetEstadoCuenta.wsSolpdfRequest request) {
            return base.Channel.wsSolpdfAsync(request);
        }
    }
}
