//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCuentas.WSValidaEmpresa {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:soap-fault:details")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:wsecweb", ConfigurationName="WSValidaEmpresa.wsecwebObj")]
    public interface wsecwebObj {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BBCuentas.WSValidaEmpresa.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BBCuentas.WSValidaEmpresa.wsEcwebResponse wsEcweb(BBCuentas.WSValidaEmpresa.wsEcwebRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BBCuentas.WSValidaEmpresa.wsEcwebResponse> wsEcwebAsync(BBCuentas.WSValidaEmpresa.wsEcwebRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsEcweb", WrapperNamespace="urn:wsecweb:wsecweb", IsWrapped=true)]
    public partial class wsEcwebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipiContrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipiGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipiCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ipcNombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ipcPrimerap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ipcSegundoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipiCp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ipcFecha;
        
        public wsEcwebRequest() {
        }
        
        public wsEcwebRequest(System.Nullable<int> ipiContrato, System.Nullable<int> ipiGrupo, System.Nullable<int> ipiCliente, string ipcNombre, string ipcPrimerap, string ipcSegundoap, System.Nullable<int> ipiCp, string ipcFecha) {
            this.ipiContrato = ipiContrato;
            this.ipiGrupo = ipiGrupo;
            this.ipiCliente = ipiCliente;
            this.ipcNombre = ipcNombre;
            this.ipcPrimerap = ipcPrimerap;
            this.ipcSegundoap = ipcSegundoap;
            this.ipiCp = ipiCp;
            this.ipcFecha = ipcFecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsEcwebResponse", WrapperNamespace="urn:wsecweb:wsecweb", IsWrapped=true)]
    public partial class wsEcwebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> opiCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string opcMensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> opiIdcontrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> opiEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> opiGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:wsecweb:wsecweb", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> opiCliente;
        
        public wsEcwebResponse() {
        }
        
        public wsEcwebResponse(string result, System.Nullable<int> opiCodigo, string opcMensaje, System.Nullable<int> opiIdcontrato, System.Nullable<int> opiEmpresa, System.Nullable<int> opiGrupo, System.Nullable<int> opiCliente) {
            this.result = result;
            this.opiCodigo = opiCodigo;
            this.opcMensaje = opcMensaje;
            this.opiIdcontrato = opiIdcontrato;
            this.opiEmpresa = opiEmpresa;
            this.opiGrupo = opiGrupo;
            this.opiCliente = opiCliente;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsecwebObjChannel : BBCuentas.WSValidaEmpresa.wsecwebObj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsecwebObjClient : System.ServiceModel.ClientBase<BBCuentas.WSValidaEmpresa.wsecwebObj>, BBCuentas.WSValidaEmpresa.wsecwebObj {
        
        public wsecwebObjClient() {
        }
        
        public wsecwebObjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsecwebObjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsecwebObjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsecwebObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BBCuentas.WSValidaEmpresa.wsEcwebResponse BBCuentas.WSValidaEmpresa.wsecwebObj.wsEcweb(BBCuentas.WSValidaEmpresa.wsEcwebRequest request) {
            return base.Channel.wsEcweb(request);
        }
        
        public string wsEcweb(System.Nullable<int> ipiContrato, System.Nullable<int> ipiGrupo, System.Nullable<int> ipiCliente, string ipcNombre, string ipcPrimerap, string ipcSegundoap, System.Nullable<int> ipiCp, string ipcFecha, out System.Nullable<int> opiCodigo, out string opcMensaje, out System.Nullable<int> opiIdcontrato, out System.Nullable<int> opiEmpresa, out System.Nullable<int> opiGrupo, out System.Nullable<int> opiCliente) {
            BBCuentas.WSValidaEmpresa.wsEcwebRequest inValue = new BBCuentas.WSValidaEmpresa.wsEcwebRequest();
            inValue.ipiContrato = ipiContrato;
            inValue.ipiGrupo = ipiGrupo;
            inValue.ipiCliente = ipiCliente;
            inValue.ipcNombre = ipcNombre;
            inValue.ipcPrimerap = ipcPrimerap;
            inValue.ipcSegundoap = ipcSegundoap;
            inValue.ipiCp = ipiCp;
            inValue.ipcFecha = ipcFecha;
            BBCuentas.WSValidaEmpresa.wsEcwebResponse retVal = ((BBCuentas.WSValidaEmpresa.wsecwebObj)(this)).wsEcweb(inValue);
            opiCodigo = retVal.opiCodigo;
            opcMensaje = retVal.opcMensaje;
            opiIdcontrato = retVal.opiIdcontrato;
            opiEmpresa = retVal.opiEmpresa;
            opiGrupo = retVal.opiGrupo;
            opiCliente = retVal.opiCliente;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<BBCuentas.WSValidaEmpresa.wsEcwebResponse> wsEcwebAsync(BBCuentas.WSValidaEmpresa.wsEcwebRequest request) {
            return base.Channel.wsEcwebAsync(request);
        }
    }
}
