//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCuentas.AppRemota {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppRemota.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Upload", ReplyAction="http://tempuri.org/IService1/UploadResponse")]
        string Upload(System.IO.Stream input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Upload", ReplyAction="http://tempuri.org/IService1/UploadResponse")]
        System.Threading.Tasks.Task<string> UploadAsync(System.IO.Stream input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Download", ReplyAction="http://tempuri.org/IService1/DownloadResponse")]
        System.IO.Stream Download(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Download", ReplyAction="http://tempuri.org/IService1/DownloadResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadAsync(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EjecutaAppRemota", ReplyAction="http://tempuri.org/IService1/EjecutaAppRemotaResponse")]
        string EjecutaAppRemota(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EjecutaAppRemota", ReplyAction="http://tempuri.org/IService1/EjecutaAppRemotaResponse")]
        System.Threading.Tasks.Task<string> EjecutaAppRemotaAsync(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultaMySQL", ReplyAction="http://tempuri.org/IService1/ConsultaMySQLResponse")]
        string ConsultaMySQL(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultaMySQL", ReplyAction="http://tempuri.org/IService1/ConsultaMySQLResponse")]
        System.Threading.Tasks.Task<string> ConsultaMySQLAsync(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DescargaMySQL", ReplyAction="http://tempuri.org/IService1/DescargaMySQLResponse")]
        string DescargaMySQL(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DescargaMySQL", ReplyAction="http://tempuri.org/IService1/DescargaMySQLResponse")]
        System.Threading.Tasks.Task<string> DescargaMySQLAsync(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Query", ReplyAction="http://tempuri.org/IService1/QueryResponse")]
        string Query(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Query", ReplyAction="http://tempuri.org/IService1/QueryResponse")]
        System.Threading.Tasks.Task<string> QueryAsync(string vs_datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreaRegSQL", ReplyAction="http://tempuri.org/IService1/CreaRegSQLResponse")]
        string CreaRegSQL(string vs_ambiente, string vs_datos, string vs_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreaRegSQL", ReplyAction="http://tempuri.org/IService1/CreaRegSQLResponse")]
        System.Threading.Tasks.Task<string> CreaRegSQLAsync(string vs_ambiente, string vs_datos, string vs_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pub_ConaEmiPolSAPS", ReplyAction="http://tempuri.org/IService1/Pub_ConaEmiPolSAPSResponse")]
        BBCuentas.AppRemota.Pub_ConaEmiPolSAPSResponse Pub_ConaEmiPolSAPS(BBCuentas.AppRemota.Pub_ConaEmiPolSAPSRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pub_ConaEmiPolSAPS", ReplyAction="http://tempuri.org/IService1/Pub_ConaEmiPolSAPSResponse")]
        System.Threading.Tasks.Task<BBCuentas.AppRemota.Pub_ConaEmiPolSAPSResponse> Pub_ConaEmiPolSAPSAsync(BBCuentas.AppRemota.Pub_ConaEmiPolSAPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pub_FinaEmiPolSAPS", ReplyAction="http://tempuri.org/IService1/Pub_FinaEmiPolSAPSResponse")]
        BBCuentas.AppRemota.Pub_FinaEmiPolSAPSResponse Pub_FinaEmiPolSAPS(BBCuentas.AppRemota.Pub_FinaEmiPolSAPSRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pub_FinaEmiPolSAPS", ReplyAction="http://tempuri.org/IService1/Pub_FinaEmiPolSAPSResponse")]
        System.Threading.Tasks.Task<BBCuentas.AppRemota.Pub_FinaEmiPolSAPSResponse> Pub_FinaEmiPolSAPSAsync(BBCuentas.AppRemota.Pub_FinaEmiPolSAPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pub_ConaCancPolNTU", ReplyAction="http://tempuri.org/IService1/Pub_ConaCancPolNTUResponse")]
        BBCuentas.AppRemota.Pub_ConaCancPolNTUResponse Pub_ConaCancPolNTU(BBCuentas.AppRemota.Pub_ConaCancPolNTURequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pub_ConaCancPolNTU", ReplyAction="http://tempuri.org/IService1/Pub_ConaCancPolNTUResponse")]
        System.Threading.Tasks.Task<BBCuentas.AppRemota.Pub_ConaCancPolNTUResponse> Pub_ConaCancPolNTUAsync(BBCuentas.AppRemota.Pub_ConaCancPolNTURequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pub_FinaCancPolNTU", ReplyAction="http://tempuri.org/IService1/Pub_FinaCancPolNTUResponse")]
        BBCuentas.AppRemota.Pub_FinaCancPolNTUResponse Pub_FinaCancPolNTU(BBCuentas.AppRemota.Pub_FinaCancPolNTURequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pub_FinaCancPolNTU", ReplyAction="http://tempuri.org/IService1/Pub_FinaCancPolNTUResponse")]
        System.Threading.Tasks.Task<BBCuentas.AppRemota.Pub_FinaCancPolNTUResponse> Pub_FinaCancPolNTUAsync(BBCuentas.AppRemota.Pub_FinaCancPolNTURequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pub_ConaEmiPolSAPS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pub_ConaEmiPolSAPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int vi_Contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int vi_Grupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int vi_Cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string vs_Poliza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string vs_Folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string vs_Convenio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string vs_Aseguradora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string vs_FormaPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int vi_MesesAsegurados;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public int vi_NoPagos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal vd_PrimaParcial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public decimal vd_PrimaTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public decimal vd_RecPFracc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public decimal vd_GtosExpd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public decimal vd_IVA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public int vi_Ocupantes;
        
        public Pub_ConaEmiPolSAPSRequest() {
        }
        
        public Pub_ConaEmiPolSAPSRequest(
                    int vi_Contrato, 
                    int vi_Grupo, 
                    int vi_Cliente, 
                    string vs_Poliza, 
                    string vs_Folio, 
                    string vs_Convenio, 
                    string vs_Aseguradora, 
                    string vs_FormaPago, 
                    int vi_MesesAsegurados, 
                    int vi_NoPagos, 
                    decimal vd_PrimaParcial, 
                    decimal vd_PrimaTotal, 
                    decimal vd_RecPFracc, 
                    decimal vd_GtosExpd, 
                    decimal vd_IVA, 
                    int vi_Ocupantes) {
            this.vi_Contrato = vi_Contrato;
            this.vi_Grupo = vi_Grupo;
            this.vi_Cliente = vi_Cliente;
            this.vs_Poliza = vs_Poliza;
            this.vs_Folio = vs_Folio;
            this.vs_Convenio = vs_Convenio;
            this.vs_Aseguradora = vs_Aseguradora;
            this.vs_FormaPago = vs_FormaPago;
            this.vi_MesesAsegurados = vi_MesesAsegurados;
            this.vi_NoPagos = vi_NoPagos;
            this.vd_PrimaParcial = vd_PrimaParcial;
            this.vd_PrimaTotal = vd_PrimaTotal;
            this.vd_RecPFracc = vd_RecPFracc;
            this.vd_GtosExpd = vd_GtosExpd;
            this.vd_IVA = vd_IVA;
            this.vi_Ocupantes = vi_Ocupantes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pub_ConaEmiPolSAPSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pub_ConaEmiPolSAPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Pub_ConaEmiPolSAPSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int vi_code;
        
        public Pub_ConaEmiPolSAPSResponse() {
        }
        
        public Pub_ConaEmiPolSAPSResponse(string Pub_ConaEmiPolSAPSResult, int vi_code) {
            this.Pub_ConaEmiPolSAPSResult = Pub_ConaEmiPolSAPSResult;
            this.vi_code = vi_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pub_FinaEmiPolSAPS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pub_FinaEmiPolSAPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string vs_Poliza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string vs_Folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int vi_Contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string vs_Aseguradora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string vs_FormaPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int vi_Meses;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int vi_NoPagos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal vd_PrimaParcial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal vd_PrimaTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal vd_RecPFracc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal vd_GtosExpd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public decimal vd_IVA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public int vi_Ocupantes;
        
        public Pub_FinaEmiPolSAPSRequest() {
        }
        
        public Pub_FinaEmiPolSAPSRequest(string vs_Poliza, string vs_Folio, int vi_Contrato, string vs_Aseguradora, string vs_FormaPago, int vi_Meses, int vi_NoPagos, decimal vd_PrimaParcial, decimal vd_PrimaTotal, decimal vd_RecPFracc, decimal vd_GtosExpd, decimal vd_IVA, int vi_Ocupantes) {
            this.vs_Poliza = vs_Poliza;
            this.vs_Folio = vs_Folio;
            this.vi_Contrato = vi_Contrato;
            this.vs_Aseguradora = vs_Aseguradora;
            this.vs_FormaPago = vs_FormaPago;
            this.vi_Meses = vi_Meses;
            this.vi_NoPagos = vi_NoPagos;
            this.vd_PrimaParcial = vd_PrimaParcial;
            this.vd_PrimaTotal = vd_PrimaTotal;
            this.vd_RecPFracc = vd_RecPFracc;
            this.vd_GtosExpd = vd_GtosExpd;
            this.vd_IVA = vd_IVA;
            this.vi_Ocupantes = vi_Ocupantes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pub_FinaEmiPolSAPSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pub_FinaEmiPolSAPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Pub_FinaEmiPolSAPSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int vi_code;
        
        public Pub_FinaEmiPolSAPSResponse() {
        }
        
        public Pub_FinaEmiPolSAPSResponse(string Pub_FinaEmiPolSAPSResult, int vi_code) {
            this.Pub_FinaEmiPolSAPSResult = Pub_FinaEmiPolSAPSResult;
            this.vi_code = vi_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pub_ConaCancPolNTU", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pub_ConaCancPolNTURequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int vi_Contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int vi_Grupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int vi_Cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string vs_FecSolicitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string vs_FecCancelacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string vs_TipoCancNTU;
        
        public Pub_ConaCancPolNTURequest() {
        }
        
        public Pub_ConaCancPolNTURequest(int vi_Contrato, int vi_Grupo, int vi_Cliente, string vs_FecSolicitud, string vs_FecCancelacion, string vs_TipoCancNTU) {
            this.vi_Contrato = vi_Contrato;
            this.vi_Grupo = vi_Grupo;
            this.vi_Cliente = vi_Cliente;
            this.vs_FecSolicitud = vs_FecSolicitud;
            this.vs_FecCancelacion = vs_FecCancelacion;
            this.vs_TipoCancNTU = vs_TipoCancNTU;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pub_ConaCancPolNTUResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pub_ConaCancPolNTUResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Pub_ConaCancPolNTUResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int vi_code;
        
        public Pub_ConaCancPolNTUResponse() {
        }
        
        public Pub_ConaCancPolNTUResponse(string Pub_ConaCancPolNTUResult, int vi_code) {
            this.Pub_ConaCancPolNTUResult = Pub_ConaCancPolNTUResult;
            this.vi_code = vi_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pub_FinaCancPolNTU", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pub_FinaCancPolNTURequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int vi_Contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string vs_FecSolicitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string vs_FecCancelacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string vs_TipoCancNTU;
        
        public Pub_FinaCancPolNTURequest() {
        }
        
        public Pub_FinaCancPolNTURequest(int vi_Contrato, string vs_FecSolicitud, string vs_FecCancelacion, string vs_TipoCancNTU) {
            this.vi_Contrato = vi_Contrato;
            this.vs_FecSolicitud = vs_FecSolicitud;
            this.vs_FecCancelacion = vs_FecCancelacion;
            this.vs_TipoCancNTU = vs_TipoCancNTU;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pub_FinaCancPolNTUResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pub_FinaCancPolNTUResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Pub_FinaCancPolNTUResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int vi_code;
        
        public Pub_FinaCancPolNTUResponse() {
        }
        
        public Pub_FinaCancPolNTUResponse(string Pub_FinaCancPolNTUResult, int vi_code) {
            this.Pub_FinaCancPolNTUResult = Pub_FinaCancPolNTUResult;
            this.vi_code = vi_code;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BBCuentas.AppRemota.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BBCuentas.AppRemota.IService1>, BBCuentas.AppRemota.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Upload(System.IO.Stream input) {
            return base.Channel.Upload(input);
        }
        
        public System.Threading.Tasks.Task<string> UploadAsync(System.IO.Stream input) {
            return base.Channel.UploadAsync(input);
        }
        
        public System.IO.Stream Download(string vs_datos) {
            return base.Channel.Download(vs_datos);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadAsync(string vs_datos) {
            return base.Channel.DownloadAsync(vs_datos);
        }
        
        public string EjecutaAppRemota(string vs_datos) {
            return base.Channel.EjecutaAppRemota(vs_datos);
        }
        
        public System.Threading.Tasks.Task<string> EjecutaAppRemotaAsync(string vs_datos) {
            return base.Channel.EjecutaAppRemotaAsync(vs_datos);
        }
        
        public string ConsultaMySQL(string vs_datos) {
            return base.Channel.ConsultaMySQL(vs_datos);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaMySQLAsync(string vs_datos) {
            return base.Channel.ConsultaMySQLAsync(vs_datos);
        }
        
        public string DescargaMySQL(string vs_datos) {
            return base.Channel.DescargaMySQL(vs_datos);
        }
        
        public System.Threading.Tasks.Task<string> DescargaMySQLAsync(string vs_datos) {
            return base.Channel.DescargaMySQLAsync(vs_datos);
        }
        
        public string Query(string vs_datos) {
            return base.Channel.Query(vs_datos);
        }
        
        public System.Threading.Tasks.Task<string> QueryAsync(string vs_datos) {
            return base.Channel.QueryAsync(vs_datos);
        }
        
        public string CreaRegSQL(string vs_ambiente, string vs_datos, string vs_sistema) {
            return base.Channel.CreaRegSQL(vs_ambiente, vs_datos, vs_sistema);
        }
        
        public System.Threading.Tasks.Task<string> CreaRegSQLAsync(string vs_ambiente, string vs_datos, string vs_sistema) {
            return base.Channel.CreaRegSQLAsync(vs_ambiente, vs_datos, vs_sistema);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BBCuentas.AppRemota.Pub_ConaEmiPolSAPSResponse BBCuentas.AppRemota.IService1.Pub_ConaEmiPolSAPS(BBCuentas.AppRemota.Pub_ConaEmiPolSAPSRequest request) {
            return base.Channel.Pub_ConaEmiPolSAPS(request);
        }
        
        public string Pub_ConaEmiPolSAPS(
                    int vi_Contrato, 
                    int vi_Grupo, 
                    int vi_Cliente, 
                    string vs_Poliza, 
                    string vs_Folio, 
                    string vs_Convenio, 
                    string vs_Aseguradora, 
                    string vs_FormaPago, 
                    int vi_MesesAsegurados, 
                    int vi_NoPagos, 
                    decimal vd_PrimaParcial, 
                    decimal vd_PrimaTotal, 
                    decimal vd_RecPFracc, 
                    decimal vd_GtosExpd, 
                    decimal vd_IVA, 
                    int vi_Ocupantes, 
                    out int vi_code) {
            BBCuentas.AppRemota.Pub_ConaEmiPolSAPSRequest inValue = new BBCuentas.AppRemota.Pub_ConaEmiPolSAPSRequest();
            inValue.vi_Contrato = vi_Contrato;
            inValue.vi_Grupo = vi_Grupo;
            inValue.vi_Cliente = vi_Cliente;
            inValue.vs_Poliza = vs_Poliza;
            inValue.vs_Folio = vs_Folio;
            inValue.vs_Convenio = vs_Convenio;
            inValue.vs_Aseguradora = vs_Aseguradora;
            inValue.vs_FormaPago = vs_FormaPago;
            inValue.vi_MesesAsegurados = vi_MesesAsegurados;
            inValue.vi_NoPagos = vi_NoPagos;
            inValue.vd_PrimaParcial = vd_PrimaParcial;
            inValue.vd_PrimaTotal = vd_PrimaTotal;
            inValue.vd_RecPFracc = vd_RecPFracc;
            inValue.vd_GtosExpd = vd_GtosExpd;
            inValue.vd_IVA = vd_IVA;
            inValue.vi_Ocupantes = vi_Ocupantes;
            BBCuentas.AppRemota.Pub_ConaEmiPolSAPSResponse retVal = ((BBCuentas.AppRemota.IService1)(this)).Pub_ConaEmiPolSAPS(inValue);
            vi_code = retVal.vi_code;
            return retVal.Pub_ConaEmiPolSAPSResult;
        }
        
        public System.Threading.Tasks.Task<BBCuentas.AppRemota.Pub_ConaEmiPolSAPSResponse> Pub_ConaEmiPolSAPSAsync(BBCuentas.AppRemota.Pub_ConaEmiPolSAPSRequest request) {
            return base.Channel.Pub_ConaEmiPolSAPSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BBCuentas.AppRemota.Pub_FinaEmiPolSAPSResponse BBCuentas.AppRemota.IService1.Pub_FinaEmiPolSAPS(BBCuentas.AppRemota.Pub_FinaEmiPolSAPSRequest request) {
            return base.Channel.Pub_FinaEmiPolSAPS(request);
        }
        
        public string Pub_FinaEmiPolSAPS(string vs_Poliza, string vs_Folio, int vi_Contrato, string vs_Aseguradora, string vs_FormaPago, int vi_Meses, int vi_NoPagos, decimal vd_PrimaParcial, decimal vd_PrimaTotal, decimal vd_RecPFracc, decimal vd_GtosExpd, decimal vd_IVA, int vi_Ocupantes, out int vi_code) {
            BBCuentas.AppRemota.Pub_FinaEmiPolSAPSRequest inValue = new BBCuentas.AppRemota.Pub_FinaEmiPolSAPSRequest();
            inValue.vs_Poliza = vs_Poliza;
            inValue.vs_Folio = vs_Folio;
            inValue.vi_Contrato = vi_Contrato;
            inValue.vs_Aseguradora = vs_Aseguradora;
            inValue.vs_FormaPago = vs_FormaPago;
            inValue.vi_Meses = vi_Meses;
            inValue.vi_NoPagos = vi_NoPagos;
            inValue.vd_PrimaParcial = vd_PrimaParcial;
            inValue.vd_PrimaTotal = vd_PrimaTotal;
            inValue.vd_RecPFracc = vd_RecPFracc;
            inValue.vd_GtosExpd = vd_GtosExpd;
            inValue.vd_IVA = vd_IVA;
            inValue.vi_Ocupantes = vi_Ocupantes;
            BBCuentas.AppRemota.Pub_FinaEmiPolSAPSResponse retVal = ((BBCuentas.AppRemota.IService1)(this)).Pub_FinaEmiPolSAPS(inValue);
            vi_code = retVal.vi_code;
            return retVal.Pub_FinaEmiPolSAPSResult;
        }
        
        public System.Threading.Tasks.Task<BBCuentas.AppRemota.Pub_FinaEmiPolSAPSResponse> Pub_FinaEmiPolSAPSAsync(BBCuentas.AppRemota.Pub_FinaEmiPolSAPSRequest request) {
            return base.Channel.Pub_FinaEmiPolSAPSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BBCuentas.AppRemota.Pub_ConaCancPolNTUResponse BBCuentas.AppRemota.IService1.Pub_ConaCancPolNTU(BBCuentas.AppRemota.Pub_ConaCancPolNTURequest request) {
            return base.Channel.Pub_ConaCancPolNTU(request);
        }
        
        public string Pub_ConaCancPolNTU(int vi_Contrato, int vi_Grupo, int vi_Cliente, string vs_FecSolicitud, string vs_FecCancelacion, string vs_TipoCancNTU, out int vi_code) {
            BBCuentas.AppRemota.Pub_ConaCancPolNTURequest inValue = new BBCuentas.AppRemota.Pub_ConaCancPolNTURequest();
            inValue.vi_Contrato = vi_Contrato;
            inValue.vi_Grupo = vi_Grupo;
            inValue.vi_Cliente = vi_Cliente;
            inValue.vs_FecSolicitud = vs_FecSolicitud;
            inValue.vs_FecCancelacion = vs_FecCancelacion;
            inValue.vs_TipoCancNTU = vs_TipoCancNTU;
            BBCuentas.AppRemota.Pub_ConaCancPolNTUResponse retVal = ((BBCuentas.AppRemota.IService1)(this)).Pub_ConaCancPolNTU(inValue);
            vi_code = retVal.vi_code;
            return retVal.Pub_ConaCancPolNTUResult;
        }
        
        public System.Threading.Tasks.Task<BBCuentas.AppRemota.Pub_ConaCancPolNTUResponse> Pub_ConaCancPolNTUAsync(BBCuentas.AppRemota.Pub_ConaCancPolNTURequest request) {
            return base.Channel.Pub_ConaCancPolNTUAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BBCuentas.AppRemota.Pub_FinaCancPolNTUResponse BBCuentas.AppRemota.IService1.Pub_FinaCancPolNTU(BBCuentas.AppRemota.Pub_FinaCancPolNTURequest request) {
            return base.Channel.Pub_FinaCancPolNTU(request);
        }
        
        public string Pub_FinaCancPolNTU(int vi_Contrato, string vs_FecSolicitud, string vs_FecCancelacion, string vs_TipoCancNTU, out int vi_code) {
            BBCuentas.AppRemota.Pub_FinaCancPolNTURequest inValue = new BBCuentas.AppRemota.Pub_FinaCancPolNTURequest();
            inValue.vi_Contrato = vi_Contrato;
            inValue.vs_FecSolicitud = vs_FecSolicitud;
            inValue.vs_FecCancelacion = vs_FecCancelacion;
            inValue.vs_TipoCancNTU = vs_TipoCancNTU;
            BBCuentas.AppRemota.Pub_FinaCancPolNTUResponse retVal = ((BBCuentas.AppRemota.IService1)(this)).Pub_FinaCancPolNTU(inValue);
            vi_code = retVal.vi_code;
            return retVal.Pub_FinaCancPolNTUResult;
        }
        
        public System.Threading.Tasks.Task<BBCuentas.AppRemota.Pub_FinaCancPolNTUResponse> Pub_FinaCancPolNTUAsync(BBCuentas.AppRemota.Pub_FinaCancPolNTURequest request) {
            return base.Channel.Pub_FinaCancPolNTUAsync(request);
        }
    }
}
